### ISSUE TITLE
Car settings bug

### ISSUE THREAD

**Issue by corentindrouet** [CookiePLMonster/SilentPatchCMR2#4]
Steps to reproduce:
 - Start a new rally with all default options (basically just press enter all time)
 - when on the pre-race page, go to settings
 - In the left panel, there is the tire options, with a buton moving on a the long stick to select the correct parameter

I have no issue there on my computer but my dad has no long stick appearing, meaning he can't set his car for the race.
when he press enter on the tire option on the right panel, it just validate it, and the left panel is ok expect the long stick option bare missing.

Thank you for the help and for this work, well done 👍

**Comment by CookiePLMonster** [comment]
I'm really sorry for a late reply, but I'll reply anyway just for visibility - this issue seems to affect Intel GPUs and can be fixed by installing [dgVoodoo 2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2/) to the game.

I don't know whether this could be fixed from SilentPatch or not, but this should be good enough.

**Comment by SilentMRG** [comment]
I have an old potato laptop with an Intel HD Graphics 1000, and I didn't get this graphics bug, all the bars appear and the game runs like butter with the patch of my namesake Silent. :)
